add read config from yaml files
MrIceman/go-uml pull request #3
Opened 2023-11-09 16:33 UTC by cesto93

Added support to configuration based on YAML file.
You can see an example yaml and a test.
I think this could be useful.

2023-11-26 16:08 UTC, MrIceman approved these changes
LGTM

2023-11-26 16:08 UTC, MrIceman commented
@cesto93  cool, thanks for the contribution!

2023-11-26 16:10 UTC, MrIceman requested changes
There are some lint issues, if you solve the then we can merge this PR @cesto93

2023-11-28 10:29 UTC, cesto93 commented
I should have fix the lint issues with the new commit, let me know if the are others problems :)

2023-11-28 11:09 UTC, MrIceman approved these changes

2023-11-28 11:11 UTC, merged

2023-11-28 11:11 UTC, MrIceman commented
@cesto93 awesome, merged your PR. 🚀